<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16637" started-at="2018-10-19T07:10:37Z" finished-at="2018-10-19T07:10:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16637" started-at="2018-10-19T07:10:37Z" finished-at="2018-10-19T07:10:54Z">
      <class name="ExtendendReport.Testreport">
        <test-method status="PASS" signature="setextend()[pri:0, instance:ExtendendReport.Testreport@18be83e4]" name="setextend" is-config="true" duration-ms="250" started-at="2018-10-19T12:40:37Z" finished-at="2018-10-19T12:40:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setextend -->
        <test-method status="PASS" signature="setup()[pri:0, instance:ExtendendReport.Testreport@18be83e4]" name="setup" is-config="true" duration-ms="7325" started-at="2018-10-19T12:40:37Z" finished-at="2018-10-19T12:40:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="test()[pri:0, instance:ExtendendReport.Testreport@18be83e4]" name="test" duration-ms="50" started-at="2018-10-19T12:40:45Z" finished-at="2018-10-19T12:40:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [AdminLTE 2 | Log in1] but found [AdminLTE 2 | Log in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [AdminLTE 2 | Log in1] but found [AdminLTE 2 | Log in]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at ExtendendReport.Testreport.test(Testreport.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="tearown(org.testng.ITestResult)[pri:0, instance:ExtendendReport.Testreport@18be83e4]" name="tearown" is-config="true" duration-ms="2016" started-at="2018-10-19T12:40:45Z" finished-at="2018-10-19T12:40:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test status=FAILURE method=Testreport.test()[pri:0, instance:ExtendendReport.Testreport@18be83e4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:ExtendendReport.Testreport@18be83e4]" name="setup" is-config="true" duration-ms="5253" started-at="2018-10-19T12:40:47Z" finished-at="2018-10-19T12:40:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="username()[pri:0, instance:ExtendendReport.Testreport@18be83e4]" name="username" duration-ms="78" started-at="2018-10-19T12:40:52Z" finished-at="2018-10-19T12:40:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Email1] but found [Email]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Email1] but found [Email]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at ExtendendReport.Testreport.username(Testreport.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- username -->
        <test-method status="PASS" signature="tearown(org.testng.ITestResult)[pri:0, instance:ExtendendReport.Testreport@18be83e4]" name="tearown" is-config="true" duration-ms="1107" started-at="2018-10-19T12:40:52Z" finished-at="2018-10-19T12:40:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=username status=FAILURE method=Testreport.username()[pri:0, instance:ExtendendReport.Testreport@18be83e4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearown -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:ExtendendReport.Testreport@18be83e4]" name="endReport" is-config="true" duration-ms="500" started-at="2018-10-19T12:40:53Z" finished-at="2018-10-19T12:40:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- ExtendendReport.Testreport -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
